services:
  - type: web
    name: project-flux-tech-titans-arena
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npx next start -H 0.0.0.0 -p $PORT
    autoDeploy: true
